package ar.edu.unlar.veterinaria.ui;

import javax.swing.JOptionPane;

/**
 * Ventana principal de la aplicacion. Es el unico punto de entrada.
 *
 * La ventana ya esta disenada. Complete unicamente los metodos marcados con TODO.
 */
public class Principal extends javax.swing.JFrame {

    // Referencia a la ventana de turnos, para el control de duplicados (PUNTO 1).
    private TurnoForm ventanaTurnos;

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitulo = new javax.swing.JLabel();
        jlblAyuda = new javax.swing.JLabel();
        jmbBarraMenu = new javax.swing.JMenuBar();
        menuGestion = new javax.swing.JMenu();
        jmiTurnos = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Veterinaria Patitas");

        jlblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setText("Clinica Veterinaria Patitas");
        getContentPane().add(jlblTitulo, java.awt.BorderLayout.CENTER);

        jlblAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblAyuda.setText("Menu Gestion -> Registro de turnos");
        getContentPane().add(jlblAyuda, java.awt.BorderLayout.SOUTH);

        menuGestion.setText("Gestion");

        jmiTurnos.setText("Registro de turnos");
        jmiTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTurnosActionPerformed(evt);
            }
        });
        menuGestion.add(jmiTurnos);

        jmbBarraMenu.add(menuGestion);

        menuSistema.setText("Sistema");

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        menuSistema.add(jmiSalir);

        jmbBarraMenu.add(menuSistema);

        setJMenuBar(jmbBarraMenu);

        setSize(new java.awt.Dimension(640, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * PUNTO 1 - Abre la ventana de registro de turnos.
     *
     * Requisitos:
     *  - Al cerrar esa ventana, la aplicacion NO debe terminar.
     *  - Por mas veces que se elija la opcion del menu, no deben acumularse
     *    ventanas de turnos: si ya hay una abierta, se trae al frente.
     *  - Debe funcionar tambien si el usuario cierra la ventana y la reabre.
     */
    private void jmiTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTurnosActionPerformed
        // TODO
    }//GEN-LAST:event_jmiTurnosActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        int r = JOptionPane.showConfirmDialog(this, "Desea salir de la aplicacion?",
                "Confirmar", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jmiSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblAyuda;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JMenuBar jmbBarraMenu;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiTurnos;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenu menuSistema;
    // End of variables declaration//GEN-END:variables
}
