package ar.edu.unlar.veterinaria.ui;

import ar.edu.unlar.veterinaria.objects.Mascota;
import ar.edu.unlar.veterinaria.objects.Sistema;
import ar.edu.unlar.veterinaria.objects.Tratamiento;
import ar.edu.unlar.veterinaria.objects.Turno;
import ar.edu.unlar.veterinaria.objects.Veterinario;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 * PARCIAL PRACTICO - Registro de turnos.
 *
 * La parte superior de la ventana, el panel de turnos y los botones ya estan
 * disenados. El panel "Tratamientos aplicados" esta VACIO: usted debe armarlo
 * en el disenador (PUNTO 2) y despues programarlo.
 */
public class TurnoForm extends javax.swing.JFrame {

    /** Creates new form TurnoForm */
    public TurnoForm() {
        initComponents();

        // TODO PUNTO 4: cargar los combos de mascotas, veterinarios y tratamientos
        //               con los datos que provee Sistema.getInstancia().

        // TODO PUNTO 5: preparar el modelo de la lista de tratamientos aplicados.

        // TODO PUNTO 6: preparar el modelo de la lista de turnos y mostrar
        //               los turnos que ya esten registrados en el Sistema.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        jlblFecha = new javax.swing.JLabel();
        jtfFecha = new javax.swing.JTextField();
        jlblHora = new javax.swing.JLabel();
        jtfHora = new javax.swing.JTextField();
        jlblMotivo = new javax.swing.JLabel();
        jtfMotivo = new javax.swing.JTextField();
        jlblMascota = new javax.swing.JLabel();
        jcbMascotas = new javax.swing.JComboBox<>();
        jlblVeterinario = new javax.swing.JLabel();
        jcbVeterinarios = new javax.swing.JComboBox<>();
        pnlCentro = new javax.swing.JPanel();
        pnlTratamientos = new javax.swing.JPanel();
        jlblCostoTotal = new javax.swing.JLabel();
        pnlTurnos = new javax.swing.JPanel();
        jspTurnos = new javax.swing.JScrollPane();
        jlTurnos = new javax.swing.JList<>();
        pnlBotones = new javax.swing.JPanel();
        jbGuardar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de turnos");

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del turno"));
        pnlDatos.setLayout(new java.awt.GridLayout(5, 2, 6, 6));

        jlblFecha.setText("Fecha:");
        pnlDatos.add(jlblFecha);
        pnlDatos.add(jtfFecha);

        jlblHora.setText("Hora:");
        pnlDatos.add(jlblHora);
        pnlDatos.add(jtfHora);

        jlblMotivo.setText("Motivo:");
        pnlDatos.add(jlblMotivo);
        pnlDatos.add(jtfMotivo);

        jlblMascota.setText("Mascota:");
        pnlDatos.add(jlblMascota);
        pnlDatos.add(jcbMascotas);

        jlblVeterinario.setText("Veterinario:");
        pnlDatos.add(jlblVeterinario);
        pnlDatos.add(jcbVeterinarios);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.NORTH);

        pnlCentro.setLayout(new java.awt.GridLayout(1, 2, 8, 8));

        pnlTratamientos.setBorder(javax.swing.BorderFactory.createTitledBorder("Tratamientos aplicados"));
        pnlTratamientos.setLayout(new java.awt.BorderLayout());

        jlblCostoTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlblCostoTotal.setText("Costo total: $0.0");
        pnlTratamientos.add(jlblCostoTotal, java.awt.BorderLayout.SOUTH);

        pnlCentro.add(pnlTratamientos);

        pnlTurnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Turnos registrados"));
        pnlTurnos.setLayout(new java.awt.BorderLayout());

        jspTurnos.setViewportView(jlTurnos);

        pnlTurnos.add(jspTurnos, java.awt.BorderLayout.CENTER);

        pnlCentro.add(pnlTurnos);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbGuardar.setText("Guardar turno");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        pnlBotones.add(jbGuardar);

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        pnlBotones.add(jbLimpiar);

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        pnlBotones.add(jbSalir);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(900, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /** PUNTO 6 - Construye el Turno y lo guarda en el Sistema. */
    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO
    }//GEN-LAST:event_jbGuardarActionPerformed

    /** PUNTO 6 - Deja el formulario listo para una nueva carga. */
    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO
    }//GEN-LAST:event_jbLimpiarActionPerformed

    /** Cierra esta ventana sin terminar la aplicacion. */
    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Mascota> jcbMascotas;
    private javax.swing.JComboBox<Veterinario> jcbVeterinarios;
    private javax.swing.JList<Turno> jlTurnos;
    private javax.swing.JLabel jlblCostoTotal;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblHora;
    private javax.swing.JLabel jlblMascota;
    private javax.swing.JLabel jlblMotivo;
    private javax.swing.JLabel jlblVeterinario;
    private javax.swing.JScrollPane jspTurnos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlTratamientos;
    private javax.swing.JPanel pnlTurnos;
    private javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfHora;
    private javax.swing.JTextField jtfMotivo;
    // End of variables declaration//GEN-END:variables
}
